[2025-09-19T17:01:38.664+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-19T17:01:38.695+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mayo_pipeline.validate_with_ge manual__2025-09-19T17:01:33.407937+00:00 [queued]>
[2025-09-19T17:01:38.706+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mayo_pipeline.validate_with_ge manual__2025-09-19T17:01:33.407937+00:00 [queued]>
[2025-09-19T17:01:38.707+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-09-19T17:01:38.720+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): validate_with_ge> on 2025-09-19 17:01:33.407937+00:00
[2025-09-19T17:01:38.725+0000] {standard_task_runner.py:63} INFO - Started process 222 to run task
[2025-09-19T17:01:38.728+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'mayo_pipeline', 'validate_with_ge', 'manual__2025-09-19T17:01:33.407937+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/mayo_pipeline.py', '--cfg-path', '/tmp/tmpajglhuiv']
[2025-09-19T17:01:38.732+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask validate_with_ge
[2025-09-19T17:01:38.817+0000] {task_command.py:426} INFO - Running <TaskInstance: mayo_pipeline.validate_with_ge manual__2025-09-19T17:01:33.407937+00:00 [running]> on host e345aeeb9fae
[2025-09-19T17:01:38.904+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='mayo_pipeline' AIRFLOW_CTX_TASK_ID='validate_with_ge' AIRFLOW_CTX_EXECUTION_DATE='2025-09-19T17:01:33.407937+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-19T17:01:33.407937+00:00'
[2025-09-19T17:01:38.905+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-19T17:01:38.920+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-09-19T17:01:38.921+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "/bin/bash -lc 'set -euo pipefail; echo VALIDATING && sleep 1'"]
[2025-09-19T17:01:38.931+0000] {subprocess.py:86} INFO - Output:
[2025-09-19T17:01:38.936+0000] {subprocess.py:93} INFO - VALIDATING
[2025-09-19T17:01:39.939+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-09-19T17:01:39.940+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-19T17:01:40.087+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=mayo_pipeline, task_id=validate_with_ge, run_id=manual__2025-09-19T17:01:33.407937+00:00, execution_date=20250919T170133, start_date=20250919T170138, end_date=20250919T170140
[2025-09-19T17:01:40.147+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-09-19T17:01:40.170+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-09-19T17:01:40.173+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
